version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.3-node-browsers
      - image: selenium/hub
        name: hub
      - image: selenium/node-chrome:latest
        environment:
          HUB_PORT_4444_TCP_ADDR: hub
          HUB_PORT_4444_TCP_PORT: 4444
    steps:
      - checkout
      - run:
          name: install
          command: |
            make install install-development
      - run:
          name: create data model
          command: |
            make resetdb-sqlite
      - run:
          name: type check
          command: |
            make typecheck
      - run:
          name: backend tests
          command: |
            make test-server
      - run:
          name: frontend tests
          command: |
            make test-client

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
